package cqu.hib;

// Generated 2012-11-3 15:21:06 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Url generated by hbm2java
 */
public class Url implements java.io.Serializable {

	private Integer urlid;
	private String url;
	private String keyword;
	private Date datatime;

	public Url() {
	}

	public Url(String url, String keyword, Date datatime) {
		this.url = url;
		this.keyword = keyword;
		this.datatime = datatime;
	}

	public Integer getUrlid() {
		return this.urlid;
	}

	public void setUrlid(Integer urlid) {
		this.urlid = urlid;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public Date getDatatime() {
		return this.datatime;
	}

	public void setDatatime(Date datatime) {
		this.datatime = datatime;
	}

}
